name: Deploy to GitHub Pages

on:
  push:
    paths: [ "stories/**", "src/**",".storybook/**" , ".github/workflows/storybook-deploy.yaml" ]
    branches:
      - "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'pnpm'
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm install
          build_command: pnpm run build:storybook
          path: storybook-static
          checkout: false
